# Generated by Django 3.2.5 on 2021-07-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
